

name: Test Automation Workflow

on:
  schedule:
  - cron: 30 23 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Running automation tests
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=false -DisHeadless=false

    - name: upload test logs
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
         name: Test logs
         path: logs/

    - name: upload screenshot artifact
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
         name: screenshots to upload
         path: screenshots/

    - name: upload html report
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
         name: automation report
         path: report.html

    - name: Test Execution status
      run: echo "Test Completed"

    - name: copy to gh pages folder
      run: |
          mkdir -p public/extent-report
          cp -R report.html public/extent-report
          cp -R screenshots/ public/extent-report/screenshots/
          ls -l

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4.7.3
      with:
         folder: public/extent-report
         token: ${{secrets.MYPAT123}}
         clean: true
         
    
    
